name = "microshift"
description = "Red Hat Device Edge - MicroShift"
version = "1.0.0"
modules = []
groups = []
distro = ""

[[packages]]
name = "microshift"

[[packages]]
name = "openssh"

[[packages]]
name = "openssh-server"

[[packages]]
name = "qemu-guest-agent"

[customizations]

[[customizations.sshkey]]
user = "root"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC+piUqnS+envGehwphv9JORF1R/YJ46cJEK7GtZjumK"

[[customizations.user]]
name = "ansible"
password = "$6$QECLMhjqTFVV09Fd$95AnKfO2MNl.yMqtScIC6pWVLp8GOLhBFoGCvdoWEuN4EyWrUTQE5CINMjLf/UL3SSRY3B1WXMdwAZeoQPQ8t1"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBP1ogAWldWtDgmJD/1GspAFj794HE2eHrP89Gqabju/"
groups = ["wheel"]

[customizations.timezone]
timezone = "Etc/UTC"

[customizations.locale]

[customizations.firewall]

[customizations.firewall.services]
enabled = ["ssh"]

[customizations.services]
enabled = ["microshift", "sshd"]